# Generated by Django 3.1.7 on 2021-03-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210302_0712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
