# Generated by Django 3.1.7 on 2021-03-04 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 3, 4, 8, 58, 54, 522817, tzinfo=utc))),
            ],
        ),
    ]
