# Generated by Django 3.1.7 on 2021-03-04 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 8, 59, 31, 40362, tzinfo=utc)),
        ),
    ]
