# Generated by Django 3.1.7 on 2021-03-07 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210304_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
